version: v4
managementClusterPluginVersions:
- version: v0.2.1
  supportedTKGBomVersions:
  - imagePath: tkg-bom
    tag: v1.4.0
- version: v0.10.1
  supportedTKGBomVersions:
  - imagePath: tkg-bom
    tag: v1.5.0-tf-v0.10.1
- version: v0.11.2
  supportedTKGBomVersions:
    - imagePath: tkg-bom
      tag: v1.5.1-tf-v0.11.2
- version: v0.11.4
  supportedTKGBomVersions:
    - imagePath: tkg-bom
      tag: v1.5.3-tf-v0.11.4
