AVI_CA_DATA_B64: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURtVENDQW9HZ0F3SUJBZ0lVQnpTVVplZnI0QUlQeS9WVkhaRGVyMGZoQm1jd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2ZERVNNQkFHQTFVRUNBd0pVM1J2WTJ0b2IyeHRNUkl3RUFZRFZRUUhEQWxUZEc5amEyaHZiRzB4RHpBTgpCZ05WQkFvTUJtbDRlbTVsZERFUE1BMEdBMVVFQ3d3R2FYaDZMbk5sTVJZd0ZBWURWUVFEREEweE56SXVNakF1Ck1qQXVNalF3TVJnd0ZnWUpLb1pJaHZjTkFRa0JGZ2xqZDBCcGVIb3VjMlV3SGhjTk1qSXdPRE13TVRRME1qRXoKV2hjTk1qVXdOVEkyTVRRME1qRXpXakI4TVJJd0VBWURWUVFJREFsVGRHOWphMmh2YkcweEVqQVFCZ05WQkFjTQpDVk4wYjJOcmFHOXNiVEVQTUEwR0ExVUVDZ3dHYVhoNmJtVjBNUTh3RFFZRFZRUUxEQVpwZUhvdWMyVXhGakFVCkJnTlZCQU1NRFRFM01pNHlNQzR5TUM0eU5EQXhHREFXQmdrcWhraUc5dzBCQ1FFV0NXTjNRR2w0ZWk1elpUQ0MKQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNV3RtdnpTc1Jtd0lHRDVQVGpsakdlRgp0d1owZURrWXptZGllcHQxZUJ0emxXcmZETk5zSzBla0szNS9oWDZReE9JK2grTktUcGp4THBsWlFDbHZpMmxFClM3a3hubTYvOEFWRjVyWUpndGVTQUsxTzY2UjRUYlJCMlA5WjljdnYvTVRKS0VtRG5KdjFHYkdGcTZZdFVsd3EKRzRqMW9NcnREdzFRbDNDaEFlTmtFOGRxRVo4RjBwRXAxMzI5KzBiODJ2L2xQRkJtRGVTREd3TldDV0pxbVU1WgozZzdURGVOQ0FGQ0I2OW9XcUtNRHNtcGhMRG4xUmFSNXg4V2ZNUGNBYWJHVk5LelllUEZyaENQN3lrMTZ3RDQrCmFVM0JTOUtRVHdaTVNLZ3ZZS3FOZGl4K1c3Zkc0WG1qbmdYc1YyaUx0SENoVlJIQWZiNlMrQXdOSG1YWVdtRUMKQXdFQUFhTVRNQkV3RHdZRFZSMFJCQWd3Qm9jRXJCUVU4REFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBYU81Ygp6Q2QvVy9LU0VlRUMvWTV6SFpnZjBGUDF5ZllVSnAwa2xFdVNhMU9UV3orWnRyOGNSYjdSelJyNCtHL0xHL2RSCjhZbnRWMDhveGZxZE9TY1BRYlFUaGlHcHFrSUlPM3VRYmU1Y3o1TXAySHpzSjFiM2tMdmtUMEIzcmtJUmRBdGYKcU14UDV2QTdZWDlhRzFjaXZtbDBrMHl5MVdRSm1kcDRDOEFod2c0SExXR1llS0tHZy9pTmxuVHVVMW1HL2ZpeQpmbk1Sc3AybFpqei9rWmtXRy8yeUNYOWNBa2RBSm0zVzlQQ1EvY3NrQlFuaFRaSTkyNmczR2tIQklMQjZsd0tkCkR0OFIxWEU2bm9kRGk0WVhHeWhIb1RoSmFjRUVXUXlnRjlLSHJNZEYzbFUzOEo3NWtNWEo2TkcvWlFNTUFrWCsKN2tYaXpWOEltdW92NHlOZ2lRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
AVI_CLOUD_NAME: Default-Cloud
AVI_CONTROL_PLANE_HA_PROVIDER: "true"
AVI_CONTROLLER: 172.20.20.240
AVI_DATA_NETWORK: VM-Workload
AVI_DATA_NETWORK_CIDR: 172.20.23.0/22
AVI_ENABLE: "true"
AVI_LABELS: ""
AVI_MANAGEMENT_CLUSTER_VIP_NETWORK_CIDR: 172.20.23.0/22
AVI_MANAGEMENT_CLUSTER_VIP_NETWORK_NAME: VM-Workload
AVI_PASSWORD: <encoded:eHVyenlnLWhheG5pdi0xc0F0ZGE=>
AVI_SERVICE_ENGINE_GROUP: Default-Group
AVI_USERNAME: admin
CLUSTER_CIDR: 192.168.0.0/16
CLUSTER_NAME: k8s-mgmt
CLUSTER_PLAN: prod
ENABLE_AUDIT_LOGGING: "true"
ENABLE_CEIP_PARTICIPATION: "false"
ENABLE_MHC: "true"
IDENTITY_MANAGEMENT_TYPE: none
INFRASTRUCTURE_PROVIDER: vsphere
LDAP_BIND_DN: ""
LDAP_BIND_PASSWORD: ""
LDAP_GROUP_SEARCH_BASE_DN: ""
LDAP_GROUP_SEARCH_FILTER: ""
LDAP_GROUP_SEARCH_GROUP_ATTRIBUTE: ""
LDAP_GROUP_SEARCH_NAME_ATTRIBUTE: cn
LDAP_GROUP_SEARCH_USER_ATTRIBUTE: DN
LDAP_HOST: ""
LDAP_ROOT_CA_DATA_B64: ""
LDAP_USER_SEARCH_BASE_DN: ""
LDAP_USER_SEARCH_FILTER: ""
LDAP_USER_SEARCH_NAME_ATTRIBUTE: ""
LDAP_USER_SEARCH_USERNAME: userPrincipalName
OIDC_IDENTITY_PROVIDER_CLIENT_ID: ""
OIDC_IDENTITY_PROVIDER_CLIENT_SECRET: ""
OIDC_IDENTITY_PROVIDER_GROUPS_CLAIM: ""
OIDC_IDENTITY_PROVIDER_ISSUER_URL: ""
OIDC_IDENTITY_PROVIDER_NAME: ""
OIDC_IDENTITY_PROVIDER_SCOPES: ""
OIDC_IDENTITY_PROVIDER_USERNAME_CLAIM: ""
OS_ARCH: amd64
OS_NAME: photon
OS_VERSION: "3"
SERVICE_CIDR: 100.64.0.0/13
TKG_HTTP_PROXY_ENABLED: "false"
TKG_IP_FAMILY: ipv4
VSPHERE_CONTROL_PLANE_DISK_GIB: "40"
VSPHERE_CONTROL_PLANE_ENDPOINT: 172.20.20.30
VSPHERE_CONTROL_PLANE_MEM_MIB: "8192"
VSPHERE_CONTROL_PLANE_NUM_CPUS: "2"
VSPHERE_DATACENTER: /Ixznet DC
VSPHERE_DATASTORE: /Ixznet DC/datastore/esxi01_nvme_vm_storage
VSPHERE_FOLDER: /Ixznet DC/vm/K8s
VSPHERE_INSECURE: "true"
VSPHERE_NETWORK: /Ixznet DC/network/K8s-workload
VSPHERE_PASSWORD: <encoded:TGREbmdiZVJqekZjUWJLMzZMIQ==>
VSPHERE_RESOURCE_POOL: /Ixznet DC/host/vmcluster/Resources
VSPHERE_SERVER: 172.20.20.21
VSPHERE_SSH_AUTHORIZED_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCbuEI3ageAQEQrzJRe3uwOMNhwyZ+m8nRCjDAPxFLtnffebHgS2tRdFg6Ye+KpcY7Ar2x/6IvOkP53YqgbeQ0YMBVWPl/u7u6EWmi/SlHPdOOZRCo1hfqE8wsMzGyDMKIh2DTxtaWfe7KaXXtZMRLAyrlyE/NpbFs6V7hajMjCfLDkcNjJbyJCx/cjsfJbIyUqhu6mK6I0Il7kiaB2iQMxCA9vrKUnRAxDmHwue5AHSourAvQO0KZWxhhowDeAxZ+8oGvWbTzY19KXadBkORZmYLyz8udnfRre1Ug8skKsTDYrHnuouO/sjMd5qZ4tJUdBrbEdouEf7k6DX+NOQbCrv3l2e6l6+/iVhEv96dANtBSGNy3qTdD5LqQSTqCDsHoCmw4HFZpHgqOW8QPRWfSogGx/bUT+eePJiKBI6P5JdCSClNI0RfCm8rNpDYyhwLlhdr1MCBDf5zU4zEsw3+G7AGzhtafWnZ4lpsDmZY4E12EaAD0xY6uGHKKUGTZhHDM= christofferwesen@Christoffers-MacBook-Pro.local
VSPHERE_TLS_THUMBPRINT: ""
VSPHERE_USERNAME: administrator@vsphere.ixz.se
VSPHERE_WORKER_DISK_GIB: "40"
VSPHERE_WORKER_MEM_MIB: "8192"
VSPHERE_WORKER_NUM_CPUS: "2"
