AVI_CA_DATA_B64: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNGekNDQWJ5Z0F3SUJBZ0lVYXFuTXZjb2tNQWRpc3cyWnduZTV4Slg5K0VFd0NnWUlLb1pJemowRUF3SXcKZkRFU01CQUdBMVVFQ0F3SlUzUnZZMnRvYjJ4dE1SSXdFQVlEVlFRSERBbFRkRzlqYTJodmJHMHhEekFOQmdOVgpCQW9NQm1sNGVtNWxkREVQTUEwR0ExVUVDd3dHYVhoNkxuTmxNUll3RkFZRFZRUUREQTF1YzNndGJHSXVhWGg2CkxuTmxNUmd3RmdZSktvWklodmNOQVFrQkZnbGpkMEJwZUhvdWMyVXdIaGNOTWpJd09ETXdNVFEwTmpJeFdoY04KTWpVd05USTJNVFEwTmpJeFdqQjhNUkl3RUFZRFZRUUlEQWxUZEc5amEyaHZiRzB4RWpBUUJnTlZCQWNNQ1ZOMApiMk5yYUc5c2JURVBNQTBHQTFVRUNnd0dhWGg2Ym1WME1ROHdEUVlEVlFRTERBWnBlSG91YzJVeEZqQVVCZ05WCkJBTU1EVzV6ZUMxc1lpNXBlSG91YzJVeEdEQVdCZ2txaGtpRzl3MEJDUUVXQ1dOM1FHbDRlaTV6WlRCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJHT3hYNXU2QVpGc1MrRzMrNE1xRnowdUM4V3R1NjRTbFZMbApDOEc3RzNUQ2hMK1hyZTdYVHFlcWQ3aHNNY0I0d0hUUnFvQjFLQmtNMTdXbUdTMWUrS1NqSERBYU1CZ0dBMVVkCkVRUVJNQStDRFc1emVDMXNZaTVwZUhvdWMyVXdDZ1lJS29aSXpqMEVBd0lEU1FBd1JnSWhBS0d5aWN4Rm1kTVMKQWZLZ25CVTJSOVo3emhjSWRqaUt6WUFONmpKckNlUWVBaUVBdVIxRmQ5eVV3cWlOUzZWek5idU9YZjFIdC8rMQpPSTRYRTVPNm9GLy8wSjA9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
AVI_CLOUD_NAME: Default-Cloud
AVI_CONTROL_PLANE_HA_PROVIDER: "true"
AVI_CONTROLLER: nsx-lb.ixz.se
AVI_DATA_NETWORK: K8s-workload
AVI_DATA_NETWORK_CIDR: 172.20.24.0/16
AVI_ENABLE: "true"
AVI_LABELS: ""
AVI_MANAGEMENT_CLUSTER_VIP_NETWORK_CIDR: 172.20.25.0/16
AVI_MANAGEMENT_CLUSTER_VIP_NETWORK_NAME: DSwitch-Management Network
AVI_PASSWORD: <encoded:eHVyenlnLWhheG5pdi0xc0F0ZGE=>
AVI_SERVICE_ENGINE_GROUP: Default-Group
AVI_USERNAME: admin
CLUSTER_CIDR: 192.168.220.0/24
CLUSTER_NAME: k8s-mgmt
CLUSTER_PLAN: prod
ENABLE_AUDIT_LOGGING: "true"
ENABLE_CEIP_PARTICIPATION: "false"
ENABLE_MHC: "true"
IDENTITY_MANAGEMENT_TYPE: none
INFRASTRUCTURE_PROVIDER: vsphere
LDAP_BIND_DN: ""
LDAP_BIND_PASSWORD: ""
LDAP_GROUP_SEARCH_BASE_DN: ""
LDAP_GROUP_SEARCH_FILTER: ""
LDAP_GROUP_SEARCH_GROUP_ATTRIBUTE: ""
LDAP_GROUP_SEARCH_NAME_ATTRIBUTE: cn
LDAP_GROUP_SEARCH_USER_ATTRIBUTE: DN
LDAP_HOST: ""
LDAP_ROOT_CA_DATA_B64: ""
LDAP_USER_SEARCH_BASE_DN: ""
LDAP_USER_SEARCH_FILTER: ""
LDAP_USER_SEARCH_NAME_ATTRIBUTE: ""
LDAP_USER_SEARCH_USERNAME: userPrincipalName
OIDC_IDENTITY_PROVIDER_CLIENT_ID: ""
OIDC_IDENTITY_PROVIDER_CLIENT_SECRET: ""
OIDC_IDENTITY_PROVIDER_GROUPS_CLAIM: ""
OIDC_IDENTITY_PROVIDER_ISSUER_URL: ""
OIDC_IDENTITY_PROVIDER_NAME: ""
OIDC_IDENTITY_PROVIDER_SCOPES: ""
OIDC_IDENTITY_PROVIDER_USERNAME_CLAIM: ""
OS_ARCH: amd64
OS_NAME: photon
OS_VERSION: "3"
SERVICE_CIDR: 192.168.110.0/24
TKG_HTTP_PROXY_ENABLED: "false"
TKG_IP_FAMILY: ipv4
VSPHERE_CONTROL_PLANE_DISK_GIB: "40"
VSPHERE_CONTROL_PLANE_ENDPOINT: ""
VSPHERE_CONTROL_PLANE_MEM_MIB: "8192"
VSPHERE_CONTROL_PLANE_NUM_CPUS: "2"
VSPHERE_DATACENTER: /Ixznet DC
VSPHERE_DATASTORE: /Ixznet DC/datastore/esxi01_nvme_vm_storage
VSPHERE_FOLDER: /Ixznet DC/vm/K8s
VSPHERE_INSECURE: "true"
VSPHERE_NETWORK: /Ixznet DC/network/K8s-workload
VSPHERE_PASSWORD: <encoded:TGREbmdiZVJqekZjUWJLMzZMIQ==>
VSPHERE_RESOURCE_POOL: /Ixznet DC/host/vmcluster/Resources
VSPHERE_SERVER: 172.20.20.21
VSPHERE_SSH_AUTHORIZED_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCbuEI3ageAQEQrzJRe3uwOMNhwyZ+m8nRCjDAPxFLtnffebHgS2tRdFg6Ye+KpcY7Ar2x/6IvOkP53YqgbeQ0YMBVWPl/u7u6EWmi/SlHPdOOZRCo1hfqE8wsMzGyDMKIh2DTxtaWfe7KaXXtZMRLAyrlyE/NpbFs6V7hajMjCfLDkcNjJbyJCx/cjsfJbIyUqhu6mK6I0Il7kiaB2iQMxCA9vrKUnRAxDmHwue5AHSourAvQO0KZWxhhowDeAxZ+8oGvWbTzY19KXadBkORZmYLyz8udnfRre1Ug8skKsTDYrHnuouO/sjMd5qZ4tJUdBrbEdouEf7k6DX+NOQbCrv3l2e6l6+/iVhEv96dANtBSGNy3qTdD5LqQSTqCDsHoCmw4HFZpHgqOW8QPRWfSogGx/bUT+eePJiKBI6P5JdCSClNI0RfCm8rNpDYyhwLlhdr1MCBDf5zU4zEsw3+G7AGzhtafWnZ4lpsDmZY4E12EaAD0xY6uGHKKUGTZhHDM= christofferwesen@Christoffers-MacBook-Pro.local
VSPHERE_TLS_THUMBPRINT: ""
VSPHERE_USERNAME: administrator@vsphere.ixz.se
VSPHERE_WORKER_DISK_GIB: "40"
VSPHERE_WORKER_MEM_MIB: "8192"
VSPHERE_WORKER_NUM_CPUS: "2"
