release:
    version: v0.11.4
images:
    all:
        repository: projects.registry.vmware.com/tkg/tanzu-framework-release/cluster-api
    cert-manager:
        repository: projects.registry.vmware.com/tkg/tanzu-framework-release
        tag: v1.5.3_vmware.2
cert-manager:
    url: /Users/chrwes/.config/tanzu/tkg/providers/cert-manager/v1.5.3/cert-manager.yaml
    version: v1.5.3
providers:
    - name: cluster-api
      url: /Users/chrwes/.config/tanzu/tkg/providers/cluster-api/v1.0.1/core-components.yaml
      type: CoreProvider
    - name: aws
      url: /Users/chrwes/.config/tanzu/tkg/providers/infrastructure-aws/v1.2.0/infrastructure-components.yaml
      type: InfrastructureProvider
    - name: vsphere
      url: /Users/chrwes/.config/tanzu/tkg/providers/infrastructure-vsphere/v1.0.3/infrastructure-components.yaml
      type: InfrastructureProvider
    - name: azure
      url: /Users/chrwes/.config/tanzu/tkg/providers/infrastructure-azure/v1.0.2/infrastructure-components.yaml
      type: InfrastructureProvider
    - name: tkg-service-vsphere
      url: /Users/chrwes/.config/tanzu/tkg/providers/infrastructure-tkg-service-vsphere/v1.1.0/unused.yaml
      type: InfrastructureProvider
    - name: kubeadm
      url: /Users/chrwes/.config/tanzu/tkg/providers/bootstrap-kubeadm/v1.0.1/bootstrap-components.yaml
      type: BootstrapProvider
    - name: kubeadm
      url: /Users/chrwes/.config/tanzu/tkg/providers/control-plane-kubeadm/v1.0.1/control-plane-components.yaml
      type: ControlPlaneProvider
    - name: docker
      url: /Users/chrwes/.config/tanzu/tkg/providers/infrastructure-docker/v1.0.1/infrastructure-components.yaml
      type: InfrastructureProvider
